


FROM mcr.microsoft.com/devcontainers/base:bookworm

#  https://github.com/devcontainers/images/tree/main/src/base-debian
#  从 buildpack-deps(https://github.com/docker-library/buildpack-deps) 安装bookworm-curl获得基本开发组件（带有curl 包） 
#  feature 安装 common-utils 和 git